services:
  database:
    image: mongo:latest
    container_name: mongodb_tp
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  gui:
    image: mongo-express:latest
    container_name: mongo_express_tp
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database

volumes:
  mongo-data: